---
aap_hostname: "{{ aap_host | default(groups['automationgateway'][0]) }}:{{ gateway_port | default(443) }}"
aap_username: "{{ aap_user | default('admin') }}"
aap_password: "{{ aap_pass }}"
aap_validate_certs: false
...