---
configs_directory: "../configs"


config_controller_applications: true
config_controller_bulk_hosts: true
config_controller_credential_input_sources: true
config_controller_credential_types: true
config_controller_credentials: true
config_controller_execution_environments: true
config_controller_hosts: true
config_controller_host_groups: true
config_controller_instance_groups: true
config_controller_instances: true
config_controller_inventories: true
config_controller_inventory_sources: true
config_controller_job_templates: true
config_controller_labels: true
config_controller_notification_templates: true
config_controller_projects: true
config_controller_roles: true
config_controller_schedules: true
config_controller_settings: true
config_controller_workflow_job_templates: true

config_eda_credential_types: true
config_eda_credentials: true
config_eda_controller_tokens: true
config_eda_projects: true
config_eda_event_streams: true
config_eda_decision_environments: true
config_eda_rulebook_activations: true


config_gateway_applications: true
config_gateway_authenticator_maps: true
config_gateway_authenticators: true
config_gateway_http_ports: true
config_gateway_organizations: true
config_gateway_role_user_assignments: true
config_gateway_routes: true
config_gateway_service_clusters: true
config_gateway_service_keys: true
config_gateway_service_nodes: true
config_gateway_services: true
config_gateway_settings: true
config_gateway_teams: true
config_gateway_users: true


gateway_configuration_items:
  - name: gateway_authenticators
    directory: "gateway/gateway_authenticators"
    default_attr: "ansible_facts.gateway_authenticators"
    env_attr: "ansible_facts.gateway_authenticators_{{ env }}"
    role_name: "infra.aap_configuration.gateway_authenticators"
  - name: gateway_authenticator_maps
    directory: "gateway/gateway_authenticator_maps"
    default_attr: "ansible_facts.gateway_authenticator_maps"
    env_attr: "ansible_facts.gateway_authenticator_maps_{{ env }}"
    role_name: "infra.aap_configuration.gateway_authenticator_maps"
  - name: gateway_settings
    directory: "gateway/gateway_settings"
    default_attr: "ansible_facts.gateway_settings"
    env_attr: "ansible_facts.gateway_settings_{{ env }}"
    role_name: "infra.aap_configuration.gateway_settings"
  - name: aap_organizations
    directory: "gateway/gateway_organizations"
    default_attr: "ansible_facts.aap_organizations"
    env_attr: "ansible_facts.aap_organizations_{{ env }}"
    role_name: "infra.aap_configuration.gateway_organizations"
  - name: aap_applications
    directory: "gateway/gateway_applications"
    default_attr: "ansible_facts.aap_applications"
    env_attr: "ansible_facts.aap_applications_{{ env }}"
    role_name: "infra.aap_configuration.gateway_applications"
  - name: gateway_http_ports
    directory: "gateway/gateway_http_ports"
    default_attr: "ansible_facts.gateway_http_ports"
    env_attr: "ansible_facts.gateway_http_ports_{{ env }}"
    role_name: "infra.aap_configuration.gateway_http_ports"
  - name: gateway_service_clusters
    directory: "gateway/gateway_service_clusters"
    default_attr: "ansible_facts.gateway_service_clusters"
    env_attr: "ansible_facts.gateway_service_clusters_{{ env }}"
    role_name: "infra.aap_configuration.gateway_service_clusters"
  - name: gateway_service_keys
    directory: "gateway/gateway_service_keys"
    default_attr: "ansible_facts.gateway_service_keys"
    env_attr: "ansible_facts.gateway_service_keys_{{ env }}"
    role_name: "infra.aap_configuration.gateway_service_keys"
  - name: gateway_service_nodes
    directory: "gateway/gateway_service_nodes"
    default_attr: "ansible_facts.gateway_service_nodes"
    env_attr: "ansible_facts.gateway_service_nodes_{{ env }}"
    role_name: "infra.aap_configuration.gateway_service_nodes"
  - name: gateway_services
    directory: "gateway/gateway_services"
    default_attr: "ansible_facts.gateway_services"
    env_attr: "ansible_facts.gateway_services_{{ env }}"
    role_name: "infra.aap_configuration.gateway_services"
  - name: aap_teams
    directory: "gateway/gateway_teams"
    default_attr: "ansible_facts.aap_teams"
    env_attr: "ansible_facts.aap_teams_{{ env }}"
    role_name: "infra.aap_configuration.gateway_teams"
  - name: aap_user_accounts
    directory: "gateway/gateway_users"
    default_attr: "ansible_facts.aap_user_accounts"
    env_attr: "ansible_facts.aap_user_accounts_{{ env }}"
    role_name: "infra.aap_configuration.gateway_users"
  - name: gateway_role_user_assignments
    directory: "gateway/gateway_role_user_assignments"
    default_attr: "ansible_facts.gateway_role_user_assignments"
    env_attr: "ansible_facts.gateway_role_user_assignments_{{ env }}"
    role_name: "infra.aap_configuration.gateway_role_user_assignments"
  - name: gateway_routes
    directory: "gateway/gateway_routes"
    default_attr: "ansible_facts.gateway_routes"
    env_attr: "ansible_facts.gateway_routes_{{ env }}"
    role_name: "infra.aap_configuration.gateway_routes"

hub_configuration_items:
  - name: hub_namespace
    directory: "hub/hub_namespace"
    default_attr: "ansible_facts.hub_namespaces"
    env_attr: "ansible_facts.hub_namespaces_{{ env }}"
    role_name: "infra.aap_configuration.hub_namespace"
  - name: hub_collection
    directory: "hub/hub_collection"
    default_attr: "ansible_facts.hub_collections"
    env_attr: "ansible_facts.hub_collections_{{ env }}"
    role_name: "infra.aap_configuration.hub_collection"
  - name: hub_ee_registry
    directory: "hub/hub_ee_registry"
    default_attr: "ansible_facts.hub_ee_registries"
    env_attr: "ansible_facts.hub_ee_registries_{{ env }}"
    role_name: "infra.aap_configuration.hub_ee_registry"
  - name: hub_ee_repository
    directory: "hub/hub_ee_repository"
    default_attr: "ansible_facts.hub_ee_repositories"
    env_attr: "ansible_facts.hub_ee_repositories_{{ env }}"
    role_name: "infra.aap_configuration.hub_ee_repository"
  - name: hub_ee_repository
    directory: "hub/hub_ee_repository"
    default_attr: "ansible_facts.hub_ee_repositories"
    env_attr: "ansible_facts.hub_ee_repositories_{{ env }}"
    role_name: "infra.aap_configuration.hub_ee_repository"
  - name: hub_ee_image
    directory: "hub/hub_ee_image"
    default_attr: "ansible_facts.hub_ee_images"
    env_attr: "ansible_facts.hub_ee_images_{{ env }}"
    role_name: "infra.aap_configuration.hub_ee_image"
  - name: hub_collection_remote
    directory: "hub/hub_collection_remote"
    default_attr: "ansible_facts.hub_collection_remotes"
    env_attr: "ansible_facts.hub_collection_remotes_{{ env }}"
    role_name: "infra.aap_configuration.hub_collection_remote"
  - name: hub_collection_repository
    directory: "hub/hub_collection_repository"
    default_attr: "ansible_facts.hub_collection_repositories"
    env_attr: "ansible_facts.hub_collection_repositories_{{ env }}"
    role_name: "infra.aap_configuration.hub_collection_repository"

controller_configuration_items:
  - name: controller_settings
    directory: "controller/controller_settings"
    default_attr: "ansible_facts.controller_settings"
    env_attr: "ansible_facts.controller_settings_{{ env }}"
    role_name: "infra.aap_configuration.controller_settings"
  - name: controller_instances
    directory: "controller/controller_instances"
    default_attr: "ansible_facts.controller_instances"
    env_attr: "ansible_facts.controller_instances_{{ env }}"
    role_name: "infra.aap_configuration.controller_instances"
  - name: controller_instance_groups
    directory: "controller/controller_instance_groups"
    default_attr: "ansible_facts.controller_instance_groups"
    env_attr: "ansible_facts.controller_instance_groups_{{ env }}"
    role_name: "infra.aap_configuration.controller_instance_groups"
  - name: controller_labels
    directory: "controller/controller_labels"
    default_attr: "ansible_facts.controller_labels"
    env_attr: "ansible_facts.controller_labels_{{ env }}"
    role_name: "infra.aap_configuration.controller_labels"
  - name: controller_credential_types
    directory: "controller/controller_credential_types"
    default_attr: "ansible_facts.controller_credential_types"
    env_attr: "ansible_facts.controller_credential_types_{{ env }}"
    role_name: "infra.aap_configuration.controller_credential_types"
  - name: controller_credentials
    directory: "controller/controller_credentials"
    default_attr: "ansible_facts.controller_credentials"
    env_attr: "ansible_facts.controller_credentials_{{ env }}"
    role_name: "infra.aap_configuration.controller_credentials"
  - name: controller_credential_input_sources
    directory: "controller/controller_credential_input_sources"
    default_attr: "ansible_facts.controller_credential_input_sources"
    env_attr: "ansible_facts.controller_credential_input_sources_{{ env }}"
    role_name: "infra.aap_configuration.controller_credential_input_sources"
  - name: controller_execution_environments
    directory: "controller/controller_execution_environments"
    default_attr: "ansible_facts.controller_execution_environments"
    env_attr: "ansible_facts.controller_execution_environments_{{ env }}"
    role_name: "infra.aap_configuration.controller_execution_environments"
  - name: aap_applications
    directory: "controller/controller_applications"
    default_attr: "ansible_facts.aap_applications"
    env_attr: "ansible_facts.aap_applications_{{ env }}"
    role_name: "infra.aap_configuration.controller_applications"
  - name: controller_notification_templates
    directory: "controller/controller_notification_templates"
    default_attr: "ansible_facts.controller_notifications"
    env_attr: "ansible_facts.controller_notifications_{{ env }}"
    role_name: "infra.aap_configuration.controller_notification_templates"
  - name: controller_projects
    directory: "controller/controller_projects"
    default_attr: "ansible_facts.controller_projects"
    env_attr: "ansible_facts.controller_projects_{{ env }}"
    role_name: "infra.aap_configuration.controller_projects"
  - name: controller_inventories
    directory: "controller/controller_inventories"
    default_attr: "ansible_facts.controller_inventories"
    env_attr: "ansible_facts.controller_inventories_{{ env }}"
    role_name: "infra.aap_configuration.controller_inventories"
  - name: controller_inventory_sources
    directory: "controller/controller_inventory_sources"
    default_attr: "ansible_facts.controller_inventory_sources"
    env_attr: "ansible_facts.controller_inventory_sources_{{ env }}"
    role_name: "infra.aap_configuration.controller_inventory_sources"
  - name: controller_hosts
    directory: "controller/controller_hosts"
    default_attr: "ansible_facts.controller_hosts"
    env_attr: "ansible_facts.controller_hosts_{{ env }}"
    role_name: "infra.aap_configuration.controller_hosts"
  - name: controller_bulk_host_create
    directory: "controller/controller_bulk_host_create"
    default_attr: "ansible_facts.controller_bulk_hosts"
    env_attr: "ansible_facts.controller_bulk_hosts_{{ env }}"
    role_name: "infra.aap_configuration.controller_bulk_host_create"
  - name: controller_host_groups
    directory: "controller/controller_host_groups"
    default_attr: "ansible_facts.controller_groups"
    env_attr: "ansible_facts.controller_groups_{{ env }}"
    role_name: "infra.aap_configuration.controller_host_groups"
  - name: controller_templates
    directory: "controller/controller_job_templates"
    default_attr: "ansible_facts.controller_templates"
    env_attr: "ansible_facts.controller_templates_{{ env }}"
    role_name: "infra.aap_configuration.controller_job_templates"
  - name: controller_workflow_job_templates
    directory: "controller/controller_workflow_job_templates"
    default_attr: "ansible_facts.controller_workflows"
    env_attr: "ansible_facts.controller_workflows_{{ env }}"
    role_name: "infra.aap_configuration.controller_workflow_job_templates"
  - name: controller_schedules
    directory: "controller/controller_schedules"
    default_attr: "ansible_facts.controller_schedules"
    env_attr: "ansible_facts.controller_schedules_{{ env }}"
    role_name: "infra.aap_configuration.controller_schedules"
  - name: controller_roles
    directory: "controller/controller_roles"
    default_attr: "ansible_facts.controller_roles"
    env_attr: "ansible_facts.controller_roles_{{ env }}"
    role_name: "infra.aap_configuration.controller_roles"

eda_configuration_items:
  - name: eda_credential_types
    directory: "eda/eda_credential_types"
    default_attr: "ansible_facts.eda_credential_types"
    env_attr: "ansible_facts.eda_credential_types_{{ env }}"
    role_name: "infra.aap_configuration.eda_credential_types"
  - name: eda_credentials
    directory: "eda/eda_credentials"
    default_attr: "ansible_facts.eda_credentials"
    env_attr: "ansible_facts.eda_credentials_{{ env }}"
    role_name: "infra.aap_configuration.eda_credentials"
  - name: eda_controller_tokens
    directory: "eda/eda_controller_tokens"
    default_attr: "ansible_facts.eda_controller_tokens"
    env_attr: "ansible_facts.eda_controller_tokens_{{ env }}"
    role_name: "infra.aap_configuration.eda_controller_tokens"
  - name: eda_projects
    directory: "eda/eda_projects"
    default_attr: "ansible_facts.eda_projects"
    env_attr: "ansible_facts.eda_projects_{{ env }}"
    role_name: "infra.aap_configuration.eda_projects"
  - name: eda_event_streams
    directory: "eda/eda_event_streams"
    default_attr: "ansible_facts.eda_event_streams"
    env_attr: "ansible_facts.eda_event_streams_{{ env }}"
    role_name: "infra.aap_configuration.eda_event_streams"
  - name: eda_decision_environments
    directory: "eda/eda_decision_environments"
    default_attr: "ansible_facts.eda_decision_environments"
    env_attr: "ansible_facts.eda_decision_environments_{{ env }}"
    role_name: "infra.aap_configuration.eda_decision_environments"
  - name: eda_rulebook_activations
    directory: "eda/eda_rulebook_activations"
    default_attr: "ansible_facts.eda_rulebook_activations"
    env_attr: "ansible_facts.eda_rulebook_activations_{{ env }}"
    role_name: "infra.aap_configuration.eda_rulebook_activations"

configuration_items: >
  {{ gateway_configuration_items
   + hub_configuration_items
   + controller_configuration_items
   + eda_configuration_items }}
...