---
configs_directory: "../configs"

gateway_configuration_items:
  - name: gateway_authenticators
    directory: "gateway/gateway_authenticators"
    default_attr: "ansible_facts.gateway_authenticators"
    optional_attr: "ansible_facts.gateway_authenticators_{{ env }}"
    role_name: "infra.aap_configuration.gateway_authenticators"
  - name: gateway_authenticator_maps
    directory: "gateway/gateway_authenticator_maps"
    default_attr: "ansible_facts.gateway_authenticator_maps"
    optional_attr: "ansible_facts.gateway_authenticator_maps_{{ env }}"
    role_name: "infra.aap_configuration.gateway_authenticator_maps"
  - name: gateway_settings
    directory: "gateway/gateway_settings"
    default_attr: "ansible_facts.gateway_settings"
    optional_attr: "ansible_facts.gateway_settings_{{ env }}"
    role_name: "infra.aap_configuration.gateway_settings"
  - name: gateway_organizations
    directory: "gateway/gateway_organizations"
    default_attr: "ansible_facts.aap_organizations"
    optional_attr: "ansible_facts.aap_organization_{{ env }}"
    role_name: "infra.aap_configuration.gateway_organizations"
  - name: aap_applications
    directory: "gateway/gateway_applications"
    default_attr: "ansible_facts.aap_applications"
    optional_attr: "ansible_facts.aap_applications_{{ env }}"
    role_name: "infra.aap_configuration.gateway_applications"
  - name: gateway_http_ports
    directory: "gateway/gateway_http_ports"
    default_attr: "ansible_facts.gateway_http_ports"
    optional_attr: "ansible_facts.gateway_http_ports_{{ env }}"
    role_name: "infra.aap_configuration.gateway_http_ports"
  - name: gateway_service_clusters
    directory: "gateway/gateway_service_clusters"
    default_attr: "ansible_facts.gateway_service_clusters"
    optional_attr: "ansible_facts.gateway_service_clusters_{{ env }}"
    role_name: "infra.aap_configuration.gateway_service_clusters"
  - name: gateway_service_keys
    directory: "gateway/gateway_service_keys"
    default_attr: "ansible_facts.gateway_service_keys"
    optional_attr: "ansible_facts.gateway_service_keys_{{ env }}"
    role_name: "infra.aap_configuration.gateway_service_keys"
  - name: gateway_service_nodes
    directory: "gateway/gateway_service_nodes"
    default_attr: "ansible_facts.gateway_service_nodes"
    optional_attr: "ansible_facts.gateway_service_nodes_{{ env }}"
    role_name: "infra.aap_configuration.gateway_service_nodes"
  - name: gateway_services
    directory: "gateway/gateway_services"
    default_attr: "ansible_facts.gateway_services"
    optional_attr: "ansible_facts.gateway_services_{{ env }}"
    role_name: "infra.aap_configuration.gateway_services"
  - name: aap_teams
    directory: "gateway/gateway_teams"
    default_attr: "ansible_facts.aap_teams"
    optional_attr: "ansible_facts.aap_teams_{{ env }}"
    role_name: "infra.aap_configuration.gateway_teams"
  - name: aap_user_accounts
    directory: "gateway/gateway_users"
    default_attr: "ansible_facts.aap_user_accounts"
    optional_attr: "ansible_facts.aap_user_accounts_{{ env }}"
    role_name: "infra.aap_configuration.gateway_users"
  - name: gateway_role_user_assignments
    directory: "gateway/gateway_role_user_assignments"
    default_attr: "ansible_facts.gateway_role_user_assignments"
    optional_attr: "ansible_facts.gateway_role_user_assignments_{{ env }}"
    role_name: "infra.aap_configuration.gateway_role_user_assignments"
  - name: gateway_routes
    directory: "gateway/gateway_routes"
    default_attr: "ansible_facts.gateway_routes"
    optional_attr: "ansible_facts.gateway_routes_{{ env }}"
    role_name: "infra.aap_configuration.gateway_routes"

hub_configuration_items: []

controller_configuration_items:
  - name: controller_settings
    directory: "controller/controller_settings"
    default_attr: "ansible_facts.controller_settings"
    optional_attr: "ansible_facts.controller_settings_{{ env }}"
    role_name: "infra.aap_configuration.controller_settings"
  - name: controller_instances
    directory: "controller/controller_instances"
    default_attr: "ansible_facts.controller_instances"
    optional_attr: "ansible_facts.controller_instances_{{ env }}"
    role_name: "infra.aap_configuration.controller_instances"
  - name: controller_instance_groups
    directory: "controller/controller_instance_groups"
    default_attr: "ansible_facts.controller_instance_groups"
    optional_attr: "ansible_facts.controller_instance_groups_{{ env }}"
    role_name: "infra.aap_configuration.controller_instance_groups"
  - name: controller_labels
    directory: "controller/controller_labels"
    default_attr: "ansible_facts.controller_labels"
    optional_attr: "ansible_facts.controller_labels_{{ env }}"
    role_name: "infra.aap_configuration.controller_labels"
  - name: controller_credentials
    directory: "controller/controller_credentials"
    default_attr: "ansible_facts.controller_credentials"
    optional_attr: "ansible_facts.controller_credentials_{{ env }}"
    role_name: "infra.aap_configuration.controller_credentials"
  - name: controller_execution_environments
    directory: "controller/controller_execution_environments"
    default_attr: "ansible_facts.controller_execution_environments"
    optional_attr: "ansible_facts.controller_execution_environments_{{ env }}"
    role_name: "infra.aap_configuration.controller_execution_environments"
  - name: controller_notifications
    directory: "controller/controller_notification_templates"
    default_attr: "ansible_facts.controller_notifications"
    optional_attr: "ansible_facts.controller_notifications_{{ env }}"
    role_name: "infra.aap_configuration.controller_notification_templates"
  - name: controller_projects
    directory: "controller/controller_projects"
    default_attr: "ansible_facts.controller_projects"
    optional_attr: "ansible_facts.controller_organization_{{ env }}"
    role_name: "infra.aap_configuration.controller_projects"
  - name: controller_inventories
    directory: "controller/controller_inventories"
    default_attr: "ansible_facts.controller_inventories"
    optional_attr: "ansible_facts.controller_inventories_{{ env }}"
    role_name: "infra.aap_configuration.controller_inventories"
  - name: controller_inventory_sources
    directory: "controller/controller_inventory_sources"
    default_attr: "ansible_facts.controller_inventory_sources"
    optional_attr: "ansible_facts.controller_inventory_sources_{{ env }}"
    role_name: "infra.aap_configuration.controller_inventory_sources"
  - name: controller_hosts
    directory: "controller/controller_hosts"
    default_attr: "ansible_facts.controller_hosts"
    optional_attr: "ansible_facts.controller_hosts_{{ env }}"
    role_name: "infra.aap_configuration.controller_hosts"
  - name: controller_host_groups
    directory: "controller/controller_host_groups"
    default_attr: "ansible_facts.controller_groups"
    optional_attr: "ansible_facts.controller_groups_{{ env }}"
    role_name: "infra.aap_configuration.controller_host_groups"
  - name: controller_job_templates
    directory: "controller/controller_job_templates"
    default_attr: "ansible_facts.controller_templates"
    optional_attr: "ansible_facts.controller_templates_{{ env }}"
    role_name: "infra.aap_configuration.controller_job_templates"
  - name: controller_workflows
    directory: "controller/controller_workflow_job_templates"
    default_attr: "ansible_facts.controller_workflows"
    optional_attr: "ansible_facts.controller_workflows_{{ env }}"
    role_name: "infra.aap_configuration.controller_workflow_job_templates"
  - name: controller_schedules
    directory: "controller/controller_schedules"
    default_attr: "ansible_facts.controller_schedules"
    optional_attr: "ansible_facts.controller_schedules_{{ env }}"
    role_name: "infra.aap_configuration.controller_schedules"
  - name: controller_roles
    directory: "controller/controller_roles"
    default_attr: "ansible_facts.controller_roles"
    optional_attr: "ansible_facts.controller_roles_{{ env }}"
    role_name: "infra.aap_configuration.controller_roles"

eda_configuration_items: []

configuration_items: >
  {{ gateway_configuration_items
   + hub_configuration_items
   + controller_configuration_items
   + eda_configuration_items }}
...