---
- name: Collect configurations | hub_repository & hub_repository_sync
  ansible.builtin.include_tasks:
    file: "configure_items.yml"
  vars:
    __configure_aap_dir: "{{ item['directory'] }}"
    __configure_aap_setting: "{{ item['name'] }}"
    __configure_var_name: "{{ item['default_attr'] }}"
    __configure_var_env_name: "{{ item['env_attr'] }}"
  loop: "{{ configuration_items }}"
  when:
    - item['name'] == 'hub_repositories'

- name: INCLUDE_ROLE | infra.aap_configuration.hub_repository
  ansible.builtin.include_role:
    name: infra.aap_configuration.hub_repository
  when:
    - hub_collection_repositories is defined
    - hub_collection_repositories | length > 0

- name: INCLUDE_ROLE | infra.aap_configuration.hub_repository_sync
  ansible.builtin.include_role:
    name: infra.aap_configuration.hub_repository_sync
  when:
    - hub_collection_repositories is defined
    - hub_collection_repositories | length > 0
...
