---
- name: Collect configurations | gateway_service_keys
  ansible.builtin.include_tasks:
    file: "configure_items.yml"
  vars:
    __configure_aap_dir: "{{ item['directory'] }}"
    __configure_aap_setting: "{{ item['name'] }}"
    __configure_var_name: "{{ item['default_attr'] }}"
    __configure_var_env_name: "{{ item['env_attr'] }}"
  loop: "{{ configuration_items }}"
  when:
    - item['name'] == 'gateway_service_keys'

- name: INCLUDE_ROLE | infra.aap_configuration.gateway_service_keys
  ansible.builtin.include_role:
    name: infra.aap_configuration.gateway_service_keys
  when:
    - gateway_service_keys is defined
    - gateway_service_keys | length > 0
...
