---
- name: Collect configurations | controller_bulk_hosts_create
  ansible.builtin.include_tasks:
    file: "configure_items.yml"
  vars:
    __configure_aap_dir: "{{ item['directory'] }}"
    __configure_aap_setting: "{{ item['name'] }}"
    __configure_var_name: "{{ item['default_attr'] }}"
    __configure_var_env_name: "{{ item['env_attr'] }}"
  loop: "{{ configuration_items }}"
  when:
    - item['name'] == 'controller_bulk_host_create'

- name: INCLUDE_ROLE | infra.aap_configuration.controller_bulk_hosts_create
  ansible.builtin.include_role:
    name: infra.aap_configuration.controller_bulk_hosts_create
  when:
    - controller_bulk_hosts is defined
    - controller_bulk_hosts | length > 0
...
