---
- name: Collect configurations | gateway_organizations
  ansible.builtin.include_tasks:
    file: "configure_items.yml"
  vars:
    __configure_aap_dir: "{{ item['directory'] }}"
    __configure_aap_setting: "{{ item['name'] }}"
    __configure_var_name: "{{ item['default_attr'] }}"
    __configure_var_env_name: "{{ item['env_attr'] }}"
  loop: "{{ configuration_items }}"
  when:
    - item['name'] == 'aap_organizations'

- name: INCLUDE_ROLE | infra.aap_configuration.gateway_organizations
  ansible.builtin.include_role:
    name: infra.aap_configuration.gateway_organizations
  when:
    - aap_organizations is defined
    - aap_organizations | length > 0
...
