---
- name: Collect configurations | eda_projects
  ansible.builtin.include_tasks:
    file: "configure_items.yml"
  vars:
    __configure_aap_dir: "{{ item['directory'] }}"
    __configure_aap_setting: "{{ item['name'] }}"
    __configure_var_name: "{{ item['default_attr'] }}"
    __configure_var_env_name: "{{ item['env_attr'] }}"
  loop: "{{ configuration_items }}"
  when:
    - item['name'] == 'eda_projects'

- name: INCLUDE_ROLE | infra.aap_configuration.eda_projects
  ansible.builtin.include_role:
    name: infra.aap_configuration.eda_projects
  when:
    - eda_projects is defined
    - eda_projects | length > 0
...
