---
- name: Collect configurations | controller_job_templates
  ansible.builtin.include_tasks:
    file: "configure_items.yml"
  vars:
    __configure_aap_dir: "{{ item['directory'] }}"
    __configure_aap_setting: "{{ item['name'] }}"
    __configure_var_name: "{{ item['default_attr'] }}"
    __configure_var_env_name: "{{ item['env_attr'] }}"
  loop: "{{ configuration_items }}"
  when:
    - item['name'] == 'controller_job_templates'
  tags:
    - always

- name: INCLUDE_ROLE | infra.aap_configuration.controller_job_templates
  ansible.builtin.include_role:
    name: infra.aap_configuration.controller_job_templates
  when:
    - controller_templates is defined
    - controller_templates| length > 0
  tags:
    - always
...
