---
- name: Collect configurations | gateway_teams
  ansible.builtin.include_tasks:
    file: "configure_items.yml"
  vars:
    __configure_aap_dir: "{{ item['directory'] }}"
    __configure_aap_setting: "{{ item['name'] }}"
    __configure_var_name: "{{ item['default_attr'] }}"
    __configure_var_env_name: "{{ item['env_attr'] }}"
  loop: "{{ configuration_items }}"
  when:
    - item['name'] == 'aap_teams'

- name: INCLUDE_ROLE | infra.aap_configuration.gateway_teams
  ansible.builtin.include_role:
    name: infra.aap_configuration.gateway_teams
  when:
    - aap_teams is defined
    - aap_teams | length > 0
...
