---
- name: Collect configurations | controller_hosts & controller_host_groups
  ansible.builtin.include_tasks:
    file: "configure_items.yml"
  vars:
    __configure_aap_dir: "{{ item['directory'] }}"
    __configure_aap_setting: "{{ item['name'] }}"
    __configure_var_name: "{{ item['default_attr'] }}"
    __configure_var_env_name: "{{ item['env_attr'] }}"
  loop: "{{ configuration_items }}"
  when:
    - item['name'] == 'controller_hosts' or
      item['name'] == 'controller_host_groups'

- name: INCLUDE_ROLE | infra.aap_configuration.controller_hosts
  ansible.builtin.include_role:
    name: infra.aap_configuration.controller_hosts
  when:
    - controller_hosts is defined
    - controller_hosts | length > 0

- name: INCLUDE_ROLE | infra.aap_configuration.controller_host_groups
  ansible.builtin.include_role:
    name: infra.aap_configuration.controller_host_groups
  when:
    - controller_host_groups is defined
    - controller_host_groups | length > 0
...
