---
- name: Collect configurations | eda_controller_tokens
  ansible.builtin.include_tasks:
    file: "configure_items.yml"
  vars:
    __configure_aap_dir: "{{ item['directory'] }}"
    __configure_aap_setting: "{{ item['name'] }}"
    __configure_var_name: "{{ item['default_attr'] }}"
    __configure_var_env_name: "{{ item['env_attr'] }}"
  loop: "{{ configuration_items }}"
  when:
    - item['name'] == 'eda_controller_tokens'

- name: INCLUDE_ROLE | infra.aap_configuration.eda_controller_tokens
  ansible.builtin.include_role:
    name: infra.aap_configuration.eda_controller_tokens
  when:
    - eda_controller_tokens is defined
    - eda_controller_tokens | length > 0
...
