---
- name: Configure Ansible Automation Platform | gateway_role_user_assignments
  hosts: "{{ env | default('dev') }}"
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Include vars from vault | gateway_role_user_assignments
      ansible.builtin.include_vars:
        file: "../vaults/{{ env }}.yml"
      tags:
        - always

  tasks:
    - name: Collect configurations | gateway_role_user_assignments
      ansible.builtin.include_tasks:
        file: "configure_items.yml"
      vars:
        __configure_aap_dir: "{{ item['directory'] }}"
        __configure_aap_setting: "{{ item['name'] }}"
        __configure_var_name: "{{ item['default_attr'] }}"
        __configure_var_env_name: "{{ item['env_attr'] }}"
      loop: "{{ configuration_items }}"
      when:
        - item['name'] == 'gateway_role_user_assignments'
      tags:
        - always

    - name: INCLUDE_ROLE | infra.aap_configuration.gateway_role_user_assignments
      ansible.builtin.include_role:
        name: infra.aap_configuration.gateway_role_user_assignments
      when:
        - gateway_role_user_assignments is defined
        - gateway_role_user_assignments | length > 0
      tags:
        - always
...
