---
- name: Configure Ansible Automation Platform | eda_rulebook_activations
  hosts: "{{ env | default('dev') }}"
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Include vars from vault | eda_rulebook_activations
      ansible.builtin.include_vars:
        file: "../vaults/{{ env }}.yml"
      tags:
        - always

  tasks:
    - name: Collect configurations | eda_rulebook_activations
      ansible.builtin.include_tasks:
        file: "configure_items.yml"
      vars:
        __configure_aap_dir: "{{ item['directory'] }}"
        __configure_aap_setting: "{{ item['name'] }}"
        __configure_var_name: "{{ item['default_attr'] }}"
        __configure_var_env_name: "{{ item['env_attr'] }}"
      loop: "{{ configuration_items }}"
      when:
        - item['name'] == 'eda_rulebook_activations'
      tags:
        - always

    - name: INCLUDE_ROLE | infra.aap_configuration.eda_rulebook_activations
      ansible.builtin.include_role:
        name: infra.aap_configuration.eda_rulebook_activations
      when:
        - eda_rulebook_activations is defined
        - eda_rulebook_activations | length > 0
      tags:
        - always
...
