---
- name: Configure Ansible Automation Platform | controller_hosts & controller_host_groups
  hosts: "{{ env | default('dev') }}"
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Include vars from vault | controller_hosts & controller_host_groups
      ansible.builtin.include_vars:
        file: "../vaults/{{ env }}.yml"
      tags:
        - always

  tasks:
    - name: Collect configurations | controller_hosts & controller_host_groups
      ansible.builtin.include_tasks:
        file: "configure_items.yml"
      vars:
        __configure_aap_dir: "{{ item['directory'] }}"
        __configure_aap_setting: "{{ item['name'] }}"
        __configure_var_name: "{{ item['default_attr'] }}"
        __configure_var_env_name: "{{ item['env_attr'] }}"
      loop: "{{ configuration_items }}"
      when:
        - item['name'] == 'controller_hosts' or
          item['name'] == 'controller_host_groups'
      tags:
        - always

    - name: INCLUDE_ROLE | infra.aap_configuration.controller_hosts
      ansible.builtin.include_role:
        name: infra.aap_configuration.controller_hosts
      when:
        - controller_hosts is defined
        - controller_hosts | length > 0
      tags:
        - always

    - name: INCLUDE_ROLE | infra.aap_configuration.controller_host_groups
      ansible.builtin.include_role:
        name: infra.aap_configuration.controller_host_groups
      when:
        - controller_host_groups is defined
        - controller_host_groups | length > 0
      tags:
        - always
...
